spring:
  application:
    name: user-admin



  cloud:
    sentinel:
      enabled: false
      transport:
        dashboard: localhost:8888
      datasource:
        ds1:
          nacos:
            serverAddr: localhost:8848
            groupId: ${spring.application.name}
            dataId:  flow
            rule-type: flow
    loadbalancer:
      ribbon:
        enabled: false  #关闭RibbonLoadbalanceClient,启动spring-loadbalancer
      retry: false  #关闭重试，默认true=>开启


    circuit:
      breaker:
        enabled: false
server:
  port: 9000



ribbon:
  restclient:
    enabled: false   #改用ribbonHttpRequest
  retryableStatusCodes: 404,502,500
  ConnectTimeout: 250 # Ribbon的连接超时时间
  ReadTimeout: 1000 # Ribbon的数据读取超时时间
  OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
  MaxAutoRetriesNextServer: 0 # 切换实例的重试次数
  MaxAutoRetries: 4 # 对当前实例的重试次数


feign:
  hystrix:
    enabled: false #启动hystrix熔断  利用rtjava，响应式，并且利用线程池去执行
  sentinel:
    enabled: true  #启动sentinel熔断 SentinelInvocationHandler，同一个线程调用

    #SentinelContractHolder.parseAndValidateMetadata错误 https://blog.csdn.net/pointer_v/article/details/104989935

