spring:
  application:
    name: eureka-server

server:
  port: 7000

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
logging:
  level:
    org.springframework: info
